-- DROP TABLE titles;
CREATE TABLE titles (
	release_year int4 NULL,
	created_at timestamptz(6) NOT NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	updated_at timestamptz(6) NOT NULL,
	"name" varchar(255) NULL,
	CONSTRAINT titles_name_key UNIQUE (name),
	CONSTRAINT titles_pkey PRIMARY KEY (id)
);