-- DROP TABLE reviews;
CREATE TABLE reviews (
	rating int4 NULL,
	created_at timestamptz(6) NOT NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	title_id int8 NULL,
	updated_at timestamptz(6) NOT NULL,
	description varchar(255) NULL,
	email varchar(255) NULL,
	CONSTRAINT reviews_email_title_id_key UNIQUE (email, title_id),
	CONSTRAINT reviews_pkey PRIMARY KEY (id),
	CONSTRAINT title_id_fkey FOREIGN KEY (title_id) REFERENCES titles(id)
);