INSERT INTO reviews
(rating, created_at, title_id, updated_at, description, email) VALUES
(5, now(), 1, now(), 'George Lucas really cooked with this one, my favorite movie ever!', 'john.doe@mail.com'),
(5, now(), 1, now(), 'The lightsaber duels and the music still give me chills.', 'sarah.connor@mail.com'),
(4, now(), 1, now(), 'A timeless adventure. The practical effects still hold up amazingly well.', 'michael.smith@mail.com'),
(5, now(), 1, now(), 'Epic space opera. I grew up watching this with my dad.', 'david.johnson@mail.com'),
(4, now(), 1, now(), 'Simple story but legendary characters and world building.', 'emma.wilson@mail.com'),
(5, now(), 2, now(), 'Stylish, brutal and incredibly fun. Tarantino at his best.', 'lucas.brown@mail.com'),
(4, now(), 2, now(), 'Uma Thurman absolutely owns this role.', 'olivia.taylor@mail.com'),
(5, now(), 2, now(), 'The fight choreography is insane. Loved every minute.', 'ethan.anderson@mail.com'),
(3, now(), 2, now(), 'Cool action scenes but the pacing felt uneven sometimes.', 'ava.thomas@mail.com'),
(4, now(), 2, now(), 'A revenge story told with pure style.', 'noah.jackson@mail.com'),
(5, now(), 3, now(), 'Classic episodes are comedy gold.', 'liam.white@mail.com'),
(4, now(), 3, now(), 'One of the most influential TV shows ever.', 'isabella.harris@mail.com'),
(3, now(), 3, now(), 'Early seasons were amazing, newer ones not so much.', 'james.martin@mail.com'),
(5, now(), 3, now(), 'Still quoting Homer after all these years.', 'mia.thompson@mail.com'),
(4, now(), 3, now(), 'Smart satire disguised as a silly cartoon.', 'benjamin.garcia@mail.com'),
(5, now(), 4, now(), 'Perfect adventure movie. Marty and Doc are iconic.', 'daniel.martinez@mail.com'),
(5, now(), 4, now(), 'The time travel story is surprisingly tight and clever.', 'charlotte.robinson@mail.com'),
(4, now(), 4, now(), 'So much fun. The DeLorean is legendary.', 'henry.clark@mail.com'),
(5, now(), 4, now(), 'One of the most rewatchable movies ever made.', 'amelia.rodriguez@mail.com'),
(4, now(), 4, now(), 'Great humor and heart. A true 80s classic.', 'jack.lewis@mail.com'),
(4, now(), 5, now(), 'Comfort TV at its finest.', 'sophia.lee@mail.com'),
(5, now(), 5, now(), 'I have probably rewatched this show ten times.', 'logan.walker@mail.com'),
(4, now(), 5, now(), 'Some jokes aged poorly but still incredibly funny.', 'grace.hall@mail.com'),
(3, now(), 5, now(), 'Fun show but sometimes overrated.', 'mason.allen@mail.com'),
(5, now(), 5, now(), 'The chemistry between the cast is unbeatable.', 'chloe.young@mail.com'),
(5, now(), 6, now(), 'Visually stunning and incredibly immersive.', 'sebastian.king@mail.com'),
(4, now(), 6, now(), 'Slow but epic. The world building is fantastic.', 'lily.wright@mail.com'),
(5, now(), 6, now(), 'Hans Zimmer soundtrack goes unbelievably hard.', 'aiden.scott@mail.com'),
(4, now(), 6, now(), 'Finally a proper Dune adaptation.', 'zoe.torres@mail.com'),
(5, now(), 6, now(), 'Every frame looks like a painting.', 'samuel.nguyen@mail.com'),
(5, now(), 7, now(), 'One of the most gripping crime series ever.', 'victoria.hill@mail.com'),
(4, now(), 7, now(), 'The acting is phenomenal, especially Wagner Moura.', 'gabriel.flores@mail.com'),
(5, now(), 7, now(), 'Intense storytelling from start to finish.', 'hannah.green@mail.com'),
(4, now(), 7, now(), 'Loved the mix of Spanish and English dialogue.', 'julian.adams@mail.com'),
(5, now(), 7, now(), 'Every episode feels like a mini movie.', 'natalie.baker@mail.com'),
(2, now(), 8, now(), 'Not really my thing but I get why people liked it.', 'anthony.nelson@mail.com'),
(3, now(), 8, now(), 'A bit cheesy but nostalgic.', 'ella.carter@mail.com'),
(1, now(), 8, now(), 'I tried but the dialogue was painful.', 'isaac.mitchell@mail.com'),
(3, now(), 8, now(), 'Teen romance with vampires. Exactly what it says.', 'scarlett.perez@mail.com'),
(2, now(), 8, now(), 'Some interesting ideas but weak execution.', 'owen.roberts@mail.com'),
(5, now(), 9, now(), 'Hugh Laurie delivers one of the best TV performances ever.', 'leah.turner@mail.com'),
(4, now(), 9, now(), 'Medical mysteries plus sarcasm equals great TV.', 'caleb.phillips@mail.com'),
(5, now(), 9, now(), 'Dr. House is one of my favorite characters.', 'madison.campbell@mail.com'),
(4, now(), 9, now(), 'Formulaic but still very entertaining.', 'wyatt.parker@mail.com'),
(5, now(), 9, now(), 'Brilliant writing and great cases.', 'aubrey.evans@mail.com'),
(5, now(), 10, now(), 'Absolute masterpiece. Cinema at its peak.', 'christopher.edwards@mail.com'),
(5, now(), 10, now(), 'The scale and ambition are unmatched.', 'penelope.collins@mail.com'),
(5, now(), 10, now(), 'Extended editions are the only way to watch.', 'andrew.stewart@mail.com'),
(4, now(), 10, now(), 'Long but totally worth it.', 'lucy.sanchez@mail.com'),
(5, now(), 10, now(), 'Still the greatest fantasy adaptation ever made.', 'thomas.morris@mail.com');